services:
  devtools:
    build:
      context: .devcontainer/devtools
      dockerfile: Dockerfile
    restart: unless-stopped
    hostname: devtools
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
